// const os=require('os') -> This was taken from that wrapper parameter require...
// All contents that we write are wrapped in this anonymous function that is individual to a file 
// It is not global... This module wrapper is same as js IIFE->Immediately invoked function expression...

(function(exports,require,module,__filename,__dirname){
    // const os=require('os');
    const name="P.T.";
    console.log(name);

    // All written data inside this function is private and can't be accessed outside...
})(); //-> () means invoke immediately
// console.log(name); Name here can't be accessed...